# Generated by Django 4.2.23 on 2025-06-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_date', models.CharField(max_length=100)),
                ('match_time', models.CharField(max_length=100)),
                ('team_a', models.CharField(max_length=100)),
                ('team_b', models.CharField(max_length=100)),
                ('a_logo', models.URLField(default='logo_url')),
                ('b_logo', models.URLField(default='logo_url')),
            ],
        ),
    ]
